apiVersion: v1
kind: Service
metadata:
  name: mediai-backend-service
spec:
  selector:
    app: mediai-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer
